language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Fixtures"))`); Pkg.pin("Fixtures"); Pkg.resolve()'
  - julia -e 'using Fixtures; @assert isdefined(:Fixtures); @assert typeof(Fixtures) === Module'
  - julia ./run_tests.jl